// Generated by CoffeeScript 1.4.0
(function() {
  var verteX;

  verteX = {
    area: $('.holder.big'),
    areaPos: $('.holder.big').position(),
    areaMX: $('.mouseX'),
    areaMY: $('.mouseY'),
    HorVal: $('.HOR'),
    VerVal: $('.VER'),
    minHor: 30,
    maxHor: -30,
    minVer: 20,
    maxVer: -20,
    init: function() {
      verteX.stepsCalcul();
      return true;
    },
    stepsCalcul: function() {
      var divHeight, divWidth;
      divWidth = parseInt(verteX.area.css('width'));
      divHeight = parseInt(verteX.area.css('height'));
      verteX.HorStep = divWidth / ((Math.abs(verteX.minHor) + Math.abs(verteX.maxHor)));
      verteX.VerStep = divHeight / ((Math.abs(verteX.minVer) + Math.abs(verteX.maxVer)));
        console.log(verteX.minHor);
        console.log(verteX.maxHor);
      verteX.mouseCoordinates();
      return true;
    },
    mouseCoordinates: function() {
      return $('.holder.big').mousemove(function(e) {
        verteX.areaMX.text(e.pageX - parseInt(verteX.areaPos.left));
        verteX.areaMY.text(e.pageY - parseInt(verteX.areaPos.top));
        verteX.HorVal.text(verteX.minHor - ((e.pageX - parseInt(verteX.areaPos.left)) / verteX.HorStep));
        return true;
      });
    }
  };

  verteX.init();

}).call(this);
