// Generated by CoffeeScript 1.4.0
(function() {
  var verteX;

  verteX = {
    area: $('.holder.big'),
    areaPos: $('.holder.big').position(),
    areaMX: $('.mouseX'),
    areaMY: $('.mouseY'),
    mouseCoordinates: $('.holder.big').mousemove(function(e) {
      verteX.areaMX.text(e.pageX - verteX.areaPos.left);
      verteX.areaMY.text(e.pageY - verteX.areaPos.top);
      return true;
    })
  };

  verteX.mouseCoordinates;

}).call(this);
